-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 02 Şub 2018, 19:17:12
-- Sunucu sürümü: 10.1.29-MariaDB
-- PHP Sürümü: 7.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `veritabani`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `db1`
--

CREATE TABLE `db1` (
  `id` int(11) NOT NULL,
  `t` int(10) UNSIGNED NOT NULL DEFAULT '1512340000',
  `n` text COLLATE utf8_turkish_ci NOT NULL,
  `a` text COLLATE utf8_turkish_ci NOT NULL,
  `i` longtext COLLATE utf8_turkish_ci NOT NULL,
  `k` text COLLATE utf8_turkish_ci NOT NULL,
  `c` text COLLATE utf8_turkish_ci NOT NULL,
  `b` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `db1`
--

INSERT INTO `db1` (`id`, `t`, `n`, `a`, `i`, `k`, `c`, `b`) VALUES
(1, 1512340001, 'Çaka Bey', 'Yavuz Bahadıroğlu', 'Ağustos başlarında, çok sıcak bir gün... Akşama doğru, genç bir adam S... sokağındaki bir pansiyonda kiraladığı küçük odasından çıktı. Ağır ve kararsız adımlarla K... köprüsüne doğru yöneldi.\n\nEv sahibiyle merdivenlerde karşılaşmaktan kurtulmayı başarmıştı. Kiraladığı küçük oda, beş katlı yüksek bir evin çatı katındaydı ve odadan çok bir dolaba benziyordu. Odayı, yemek ve diğer hizmetler de dâhil olarak kiralamıştı. Ev sahibi kadın bir kat aşağıda, ayrı bir dairede oturuyordu ve genç adam her sokağa çıkışında, ev sahibesinin merdivenlere doğru ardına dek açılmış mutfak kapısının önünden geçmek zorundaydı. Buradan her geçişinde, genç adam korkuya benzer bir duygu içinde kalır, utanç duyar, yüzünü buruştururdu. Ev sahibi kadına epey borcu vardı ve onunla karşılaşmaktan çekiniyordu.\n\nKorkak ve çekingen biri değildi aslında. Tam tersine... Ama bir süredir tedirgindi. Öylesine kendi içine kapanmış, öylesine herkesten kopmuştu ki, yalnızca ev sahibesiyle değil, kiminle olursa olsun karşılaşmaktan kaçınıyordu. Ezen bir yoksulluk içindeydi ama şu son günlerde buna bile aldırdığı yoktu.', 'Roman|Tarih', 'http://www.pandora.com.tr/images/kapak/189306b.jpg', 243017),
(2, 1512340002, 'Efendi İle Uşağı', 'Tolstoy', '1870\'lerde bir kış mevsimi geçti anlatacağımız bu olay. Aziz Nikolay Yortusu\'nun ertesi günüydü.\n\nYortu köyün kilisesinde topluca kutlanmıştı, ama ikinci sınıf tüccar (*) Vasili Andreyiç Brehunov kiliseyi bir türlü bırakıp işlerinin başına dönemedi. Kilise yönetim başkanı olan tüccar, yortuyu daha sonra bir de evinde kutlayarak akraba ve tanıdıklarını ağırlamak zorundaydı. Ancak evinden son konuklar gider gitmez yol hazırlığına koyuldu.\n\nKomşu köyden bir toprak ağasının bir süre önce fiyatını kararlaştırdıkları korusunu almaya gidecekti. Kentli tüccarlar bu yağlı parçayı elinden kapmadan bitirmeliydi işini. Vasili Andreyiç\n\nkoruya yedi bin ruble verdi diye toprak ağası fiyatı 10 bine yükseltmişti. Aslına bakılırsa yedi bin ruble korunun değerinin yarısıydı. Belki Vasili Andreyiç fiyatı on binden aşağı düşürebilirdi; çünkü\n\nkoru, onun bulunduğu bucağın sınırları içindeydi ve ilçenin tüccarlarıyla aralarında varılan anlaşmaya göre, bir tüccar bir başkasının bucağında satılan malın fiyatını artıramazdı. Ne var ki, il merkezindeki kereste tüccarları göz dikmişti Goryaçkino köyü korusuna.', 'Hikaye', 'https://1.bp.blogspot.com/-Rcyz6liZdJQ/WgbevOWtMmI/AAAAAAAAAAk/c_djoGLjDxowzt2_eKmq_9SQkkxs0fY6QCLcBGAs/s1600/51p5qKZKIgL._SX312_BO1%252C204%252C203%252C200_.jpg', 163727),
(3, 1512340003, 'Kaşağı', 'Ömer Seyfettin', 'Ömer ve kardeşi Hasan, çocukluklarını büyük bir çiftlikte geçirmişlerdi. Küçük Ömer ve Hasan, en çok atlarla oynamayı, özellikle de onları tımar etmeyi seviyorlardı. Bunun için İstanbul\'dan özel getirtilen KAŞAĞI\'yı kullanıyorlardı. Ama bir gün Küçük Ömer, çocukluk heyecanıyla KAŞAĞI\'yı kırar ve suçu kardeşi Hasan\'a atar. Babası bu olaydan sonra Hasan\'a çok kızar ve ona: \n-Yalancı, der... \nHasan, bu olaydan sonra içine kapanır ve bir gün hastalanır. İşte o zaman Ömer için zor günler başlar.', 'Çocuk|Gençlik|Hikaye|Türk Klasikleri', 'https://1.bp.blogspot.com/-r3dsJnJCc4w/WgbeuOr2YDI/AAAAAAAAAAQ/6GEnqE81-acv1sOk8nqLTofIy-PWbVLCwCLcBGAs/s1600/0000000186269-1.jpg', 126346),
(4, 1512340004, 'İnsan Ne İle Yaşar', 'Tolstoy', 'Yortu köyün kilisesinde topluca kutlanmıştı, ama ikinci sınıf tüccar (*) Vasili Andreyiç Brehunov kiliseyi bir türlü bırakıp işlerinin başına dönemedi. Kilise yönetim başkanı olan tüccar, yortuyu daha sonra bir de evinde kutlayarak akraba ve tanıdıklarını ağırlamak zorundaydı. Ancak evinden son konuklar gider gitmez yol hazırlığına koyuldu. 1870\'lerde bir kış mevsimi geçti anlatacağımız bu olay. Aziz Nikolay Yortusu\'nun ertesi günüydü.\r\n\r\nKomşu köyden bir toprak ağasının bir süre önce fiyatını kararlaştırdıkları korusunu almaya gidecekti. Kentli tüccarlar bu yağlı parçayı elinden kapmadan bitirmeliydi işini.\r\n\r\nVasili Andreyiç koruya yedi bin ruble verdi diye toprak ağası fiyatı 10 bine yükseltmişti. Aslına bakılırsa yedi bin ruble korunun değerinin yarısıydı. Belki Vasili Andreyiç fiyatı on binden aşağı düşürebilirdi; çünkü koru, onun bulunduğu bucağın sınırları içindeydi ve ilçenin tüccarlarıyla aralarında varılan anlaşmaya göre, bir tüccar bir başkasının bucağında satılan malın fiyatını artıramazdı. Ne var ki, il merkezindeki kereste tüccarları göz dikmişti Goryaçkino köyü korusuna.', 'Hikaye', 'https://4.bp.blogspot.com/-kjyVDMvVVu4/WgbewUcdXBI/AAAAAAAAAA0/nDQ8K4TiAtIyKhrPCGOL3jfPm_Rs8FUrQCLcBGAs/s1600/neokur1471940366.jpg', 2121411),
(5, 1512340005, 'Tarihi Değiştiren Konuşmalar', 'Diğer', 'Dünyanın önde gelen liderlerinin kimi zaman ‘adalet’ ve ‘eşitlik’ talep eden, kimi zaman ‘teslimiyet’ ve ‘korkuyu’ itiraf eden, zaman zaman ise ‘tehdit’ içeren konuşmalarından oluşan bu kitabı okuduğunuzda, kelimelerin eylemlere nasıl ilham verdiğine şahit olacak, bundan böyle ‘söylenenlere’ daha iyi kulak kabartacaksınız.\r\n\r\nSözün gücüne inananlara…\r\n\r\nKulaklarınızı dört açın. Duyduklarınız, göreceklerinizdir!', 'Tarih|Araştırma', 'https://4.bp.blogspot.com/-6H9RIruzVrM/Wgbet9JkBKI/AAAAAAAAAAM/y5TVclakjDwfnuBZ6VWrqGUREHe69SEjgCLcBGAs/s1600/0000000175154-1.jpg', 6918558),
(6, 1512340006, 'Simyacı', 'Paulo Coelho', 'Simyacı, Brezilyalı eski şarkı sözü yazarı Paulo Coelho’nun, yayınlandığı 1988 yılından bu yana dünyayı birbirine katan, eleştirmenler tarafından bir fenomen olarak değerlendirilen üçüncü romanı. Simyacı, altı yılda kırk iki ülkede yedi milyondan fazla sattı. Bu, Gabriel Garcia Marquez’den bu yana görülmemiş bir olay. Yüreğinde, çocukluğunu yitirmemiş olan okurlar için bir klasik kimliği kazanan Simyacı’yı Saint-Exupery’nin Küçük Prens’i ve Richard Bach’ın Martı Jonathan Livingston’u ile karşılaştıranlar var (Publishers Weekly). Simyacı, İspanya’dan kalkıp Mısır Piramitlerinin eteklerinde hazinesini aramaya giden Endülüslü çoban Santiago’nun masalsı yaşamının felsefi öyküsü. Sanki bir nasihatnâme\':Yazgına nasıl egemen olacaksın, mutluluğunu nasıl kuracaksın?’ sorularına yanıt arayan bir hayat ve ahlak kılavuzu.\r\n\r\nMistik bir peri masalına benzeyen romanın altı yılda, yedi milyondan fazla okur bulmasının gizi, kuşkusuz, onun bu kılavuzluk niteliğinden kaynaklanıyor. Simyacı’yı okumak, herkes daha uykudayken, güneşin doğuşunu seyretmek için şafak vakti uyanmaya benziyor.', 'Roman', 'https://3.bp.blogspot.com/-RCuSrKPNraE/WgbeuKPaG8I/AAAAAAAAAAU/MI1qnengWRIlyUm3Ocyfpt3Fr1-PgtsAwCLcBGAs/s1600/0000000064552-1.jpg', 189270),
(7, 1512340007, 'Robin Hood', 'Howard Pyle', 'Orman koruyucusu Gilbert ve eşi Margaret Sherwood Ormanı’nda küçük ahşap bir evde yaşarlar. Margaret’in kardeşi bir gün elinde küçük bir sepetle ziyaretlerine gelir. Sepette onları küçük ve sevimli bir sürpriz beklemektedir: Bir bebek. Yıllarca hayalini kurdukları bir çocukları vardır artık. Adını Robin koyarlar. Bu küçük ahşap evde mutlu bir çocukluk süren Robin, günlerini Sherwood Ormanı’nda oynayarak geçirir. Büyüdükçe oyunları değişir; ok atmayı, kılıç kullanmayı ve avlanmayı öğrenir. Sherwood Ormanı artık Robin’in ikinci evi olmuştur.\r\n\r\nAvlanmaya çıktığı bir gün, Robin attığı oklarla iki kardeşi tuzaktan kurtarır ve evine getirir. Çocuklar kadar büyüklerin de kahramanı olacak Robin efsanesi böyle başlar. Robin arkadaşları ile birlikte ‘Şen Gençler’ çetesini kurarak halka zulüm eden Bölge Valisi ile mücadele etmeye başlar. Valinin gözünde bir asi olan Robin, halkın gözünde bir kahramandır. Başından hiç çıkarmadığı tüylü şapkasıyla zalimlere ve kötülere karşı, halkın ve iyilerin yanında savaşan bir halk kahramanıdır artık. O Robin Hood’dur.', 'Çocuk|Gençlik|Roman', 'https://2.bp.blogspot.com/-4IrjpgJR18U/WgbeviE5YyI/AAAAAAAAAAo/mU1NJKngZfIy4Mpm-y3-hjDNXxkHW1ajgCLcBGAs/s1600/93008.jpg', 1034579),
(8, 1512340008, 'Moby Dick', 'Herman Melville', '1819 yılında New York’ta dünyaya gelen Herman Melville, 1840 yılında, bir balina gemisinde başından geçen serüvenleri kitaplarının ana konusu olarak işlemiştir. Moby Dick adlı eserinde de beyaz bir balina ile hırsının esiri olan bir kaptanın sürükleyici serüvenini anlatmaktadır. Moby Dick gerek çocuklar gerekse büyüklerin beğeni ile okuduğu bir kitap olmuştur. Öyleki, daha sonraki yıllarda beyaz perdeye aktarılmış ve bu haliyle de hayranlarıyla buluşmayı başarmıştır.', 'Roman|Dünya Klasikleri', 'https://2.bp.blogspot.com/-yD2TJLuwToU/WgbewIpzE3I/AAAAAAAAAAw/IHc3bD7eA2osfn2rgG4KXp8_ntRQ2RzBQCLcBGAs/s1600/MOBY_DICK-2.jpg', 1058673),
(9, 1512340009, 'İnsancıklar', 'Dostayevski', 'Yıl 1846’dır. Genç Dostoyevski, ilk romanı İnsancıklar’ı tamamlar tamamlamaz ev arkadaşı yazar Grigoroviç’e okutur. Grigoroviç o kadar heyecanlanır ki birkaç kez kalkıp Fyodor’un boynuna sarılmak ister; fakat arkadaşının aşırı duygu gösterilerinden hoşlanmadığını bildiği için yapmaz. Grigoroviç ertesi gün romanı yazar ve yayımcı Nekrasov’a götürür; kitaptan çok etkilenen Nekrasov da eleştirmen Belinski’ye… “Yeni Gogol doğdu!” der, Nekrasov, daha kapı ağzında. Aynı günün akşamı, Belinski’ye tekrar uğradığında onu heyecan içinde bulur: “Nerede kaldınız? Nerede bu Dostoyevskiniz? Genç mi? Kaç yaşında? Hemen getirin bana onu!”\r\n\r\nBelinski’nin evine getirilen yirmi üç yaşındaki genç yazar, daha sonra orada olanları şöyle anlatacaktır: “Ve işte… beni onun yanına götürdüler. Belinski’yi birkaç yıl önce heyecanla okumuştum, ama bana ürkütücü ve sert gelmişti ve benim İnsancıklar’ımla alay edecek diye düşünüyordum. Beni çok saygılı ve ağırbaşlı bir şekilde karşıladı; ama daha bir dakika bile geçmeden her şey bambaşka oldu… Ateşli ateşli, alevli gözlerle konuşuyordu. “Siz kendiniz anlıyor musunuz?” diyordu bana tekrar tekrar, alışkanlığı olduğu üzere bağırarak, “Ne yazmış olduğunuzu anlıyor musunuz?.. Bütün bu korkunç gerçeği, bizlere göstermiş olduğunuz bu gerçeği siz mi düşündünüz? Olamaz, sizin gibi yirmi yaşında birinin bütün bunları anlamış olmasına imkân yok… Gerçeği keşfetmiş ve bir sanatçı olarak ilan etmişsiniz, size bir yetenek verilmiş, yeteneğinizin değerini bilin ve emin olun, siz büyük bir yazar olacaksınız.”\r\n\r\nYıl 2017. 171 yıl sonra Dostoyevski her kuşağın başucu yazarlarından olma özelliğini koruyor ve İnsancıklar, onun dünya edebiyatına ilk armağanı…', 'Roman', 'https://1.bp.blogspot.com/-ekJpSVAXO7k/Wgbeu5VwNSI/AAAAAAAAAAc/_OniQcvSbQY1o0A38Y7js1yUFLZ8VaGewCLcBGAs/s1600/0000000433607-1.jpg', 178620),
(10, 1512340010, 'Veba', 'Diğer', 'Camus adı çoğu okur için Yabancı romanıyla özdeşleşir. Ancak yazarın en önemli yapıtı aslında “Veba”dır. Keskin bir gözlem gücünün desteklediği arı bir bilinçle Veba, yalnızca çağımızın değil, tüm insanlık tarihinin ortak bir sorununa değinir: Felaketin yazgıya dönüşmesi.\r\n\r\nCamus’nün hiçbir yapıtında böyle acı bir yazgı, böylesine şiirsel bir dille ele alınmamıştır. “Veba”, insanın ve ışığın şiiridir. Bu şiirde renkler alabildiğine koyu, ancak yazarın sesi o denli umut doludur. Beklenmedik bir boyuta ulaşan veba salgını tüm Oranlıları ilkin umutsuzluğa boğar, ardından Doktor Rieux, Tarron ve Grand’ın gösterdikleri dayanışma örneği, başta yetkililer olmak üzere herkese bir güç ve umut kaynağı olur.', 'Roman', 'https://3.bp.blogspot.com/-EuYpCm3yHZY/Wgbew4LhooI/AAAAAAAAAA8/MKuspJrLRqkrdk94x_IwaxuJd38t4l4qQCLcBGAs/s1600/veba.jpg', 609594),
(11, 1512340011, 'Sefiller', 'Victor Hugo', 'Hugo, Sefiller adlı dev romanının önsözünü şöyle bitirir: “Yeryüzünde yoksulluk ve bilgisizliğin egemenliği sürdükçe, böylesi kitaplar gereksiz sayılmayabilir.” Yurdunun çıkarları adına siyasal kavgalardan hiç çekinmedi. Bu yüzden de tam yirmi yıl sürgünde kaldı. Sefiller de bu yılların ürünüdür (1862).\r\n\r\nBu dev romanı, genç okurlara yalınlaştırılmış, kısaltılmış biçimiyle sunuyoruz. \r\nSefiller, kürek mahkumu Jan Valjean ve polis müfettişi Javert arasında sürüp giden bir kovalamacanın hikayesi üzerine kuruludur. Jan Valjean, yoksul bir köylüdür, ailesini doyurmak amacıyla çaldığı yalnızca bir somun ekmekten dolayı kürek cezasına çarptırılmış, defalarca kaçma teşebbüsünde bulunduğundan cezası katlanmış ve on dokuz seneye cıkmıştır.\r\n\r\nFransız edebiyatının en önemli romanlarından biri olan Sefiller, romantik akımın etkilerini taşıyan bir eserdir.', 'Roman|Dünya Klasikleri', 'https://1.bp.blogspot.com/-_68nepR0vF0/WgbewbqNGtI/AAAAAAAAAA4/e1f4tGtT2tAOeSdsxBBWqFemmF111g2igCLcBGAs/s1600/image.jpg', 434518),
(12, 1512340012, 'Cumhuriyetin İlk Yüzyılı', 'İlber Ortaylı', 'Cumhuriyet’in İlk Yüzyılı’na yeni devletimizin yapı taşlarının döşendiği Osmanlı İmparatorluğu’nun modernleşme döneminden başladık.\r\n\r\nAtatürk ve silah arkadaşlarının yetiştiği II. Abdülhamid’in modernlik arayışı içinde geçen yıllarını, ama aynı zamanda istibdad günlerini ve buna karşı isyan edip hürriyet arayan genç Osmanlı subaylarının maceraları hayatları…\r\n\r\nMillî Mücadele dönemini, özgürlük havasının egemen olduğu Cumhuriyet’in ilk iki yılını ve tek partili zorlu zamanları, ardından gelen çok partili siyasal yaşamın başladığı 1950’li yılları…\r\n\r\n1913 Babıali Baskını’yla başlayan darbeler tarihini…\r\n\r\nYeni devletin ilk gününden itibaren çözmeye çalıştığı kadim problemleri; Kürt Sorunu’nu, “irtica” meselesini ve eğitim konusunu…\r\n\r\nİslâmcılıktan milliyetçiliğe, merkez sağdan sosyal demokrasiye bütün siyasal akımları…\r\n\r\n1876’dan 1924’e ve 1982’ye anayasa metinlerimizi… Bizleri 2023’e taşıyacak yeni anayasa özlemimizi…\r\n\r\nAsırlık dış politikamız, ikili ilişkilerimiz, uluslararası kuruluşlardaki temsiliyetimiz, Kıbrıs Barış Harekâtı, AB macerası ve Ortadoğu politikalarımızı…\r\n\r\nŞehirleşme, üniversiteleşme, gecekondulaşma, ekonomik büyüme, yolsuzluklar, gündelik yaşamdaki nitelik ve kalite kaybı gibi en güçlü sosyolojik dinamik ve gelişmeleri…\r\n\r\nYani bizi biz yapan ve bugünlere taşıyan önemli tarihsel dinamikleri konuştuk…\r\n\r\n“Türklerin son iki asrı bütün Doğu dünyasında ve Balkanlar’da dikkatle gözden geçirilmesi gereken büyük bir tarihî yolculuktur. Bu nedenle de Dünya Tarihi’nin önemli bir parçasıdır ve dikkatle üzerinde durulmalıdır.”', 'Tarih|Araştırma', 'https://4.bp.blogspot.com/-CBbxhbbC1Oc/Wgbev4sTXwI/AAAAAAAAAAs/neDTsrOmCEsZ7TC9-WVuUbnGUN5QAInlwCLcBGAs/s1600/cumhuriyetin-ilk-yuzyili-1923-2023-ilber-ortayli-ismail-kucukkaya.jpg', 377376),
(13, 1512340013, 'Ateşten Gömlek', 'Halide Edip Adıvar', 'Ateşten Gömlek, cepheden, romanda anlatılan kişilerle omuz omuza yaşamış birinden gelen bir yapıt. Kurtuluş Savaşı’nın ateşten gömleğinin içinden çıkmış bir roman. Halide Edib Adıvar, her birini yakından tanıdığı roman kişilerini, yani silah arkadaşlarını içtenlikle, çağına ve yaşanan acı olaylara sorumlulukla tanıklık ederek anlatıyor. Bağımsızlık savaşımızı bütün gerçekliği ve canlılığıyla anlatan belki de en önemli roman, Ateşten Gömlek.\r\n\r\nİhtilal ve isyan günlerinden beri koza, kurt, kelebek devirleri tetkik edilen mahlûkat gibi Sakarya silâh arkadaşlarımın “Ateşten Gömlek”te birkaç solgun aksini İstanbul, ihtilal ve ordu günlerinden alıp kâğıt üstüne koymaya çalıştım. İstediğim gibi olmadığı için silâh arkadaşlarımdan af dilemek isterdim. Bize onlar ilham ettiler.', 'Roman|Türk Klasikleri', 'https://3.bp.blogspot.com/-fjrIJJ6YHwQ/Wgbeue73y0I/AAAAAAAAAAY/KW2GeU0zvEUaEt1lKnyD8dQKCOq20bhMACLcBGAs/s1600/0000000238311-1.jpg', 256460),
(14, 1512340014, 'Bulut Atlası', 'Diğer', 'Bulut Atlası Tom Tykwer’ın yönetmenliğinde sinemaya uyarlandı.Başrollerini Tom Hanks, Halle Berry, Hugh Grant, Hugo Weaving ve Susan Sarandon’ın paylaştığı filmin 2012 yılına damga vurması bekleniyor. Her öykünün farklı bir dil, üslup ve teknikle anlatıldığı Bulut Atlası, roman olmaktan çok öte, insanoğlunun iktidar uğruna türdeşlerine ve doğaya verdiği zararların ve yol açtığı “kıyamet”in ele alındığı bir destan…\r\n\r\nBritish Book Edebiyat ödülü Geoffrey Faber Memorial ödülü Richard & Judy Yılın Kitabı ödülü…\r\n\r\nBooker finalisti Nebula finalisti Arthur C. Clarke finalisti Her şey birbiriyle bağlantılı Birbiriyle iç içe geçen altı hayat ve muhteşem bir macera… David Mitchell, tüm dünyayı dolaşarak, 19. yüzyıldan başlayıp kıyamet sonrası geleceğe uzanıyor. Zaman, tür ve dil sınırlarını yıkan bir anlatıyla, insanoğlunun iktidar mücadelesinin bizi nereye sürükleyebileceğine dair çarpıcı bir kehanet sunuyor.\r\n\r\n“İnsana ‘Nasıl da yazmış adam’ dedirten modern klasiklerden biri. Çağdaş edebiyata ilgi duyan herkesin mutlaka okuması gerek.”\r\nDave Eggers', 'Roman', 'https://3.bp.blogspot.com/-8Dsrsiz4uK8/Wlx2lCmxekI/AAAAAAAACy8/ZvsjSGF2kSUSMQRNiDakUqDi-Yv9QHvyACLcBGAs/s1600/indir%2B%25281%2529.jpg', 759639),
(15, 1512340015, 'Suç Ve Ceza', 'Diğer', 'Ağustos başlarında, çok sıcak bir gün... Akşama doğru, genç bir adam S... sokağındaki bir pansiyonda kiraladığı küçük odasından çıktı. Ağır ve kararsız adımlarla K... köprüsüne doğru yöneldi.\r\n\r\nEv sahibiyle merdivenlerde karşılaşmaktan kurtulmayı başarmıştı. Kiraladığı küçük oda, beş katlı yüksek bir evin çatı katındaydı ve odadan çok bir dolaba benziyordu. Odayı, yemek ve diğer hizmetler de dâhil olarak kiralamıştı. Ev sahibi kadın bir kat aşağıda, ayrı bir dairede oturuyordu ve genç adam her sokağa çıkışında, ev sahibesinin merdivenlere doğru ardına dek açılmış mutfak kapısının önünden geçmek zorundaydı. Buradan her geçişinde, genç adam korkuya benzer bir duygu içinde kalır, utanç duyar, yüzünü buruştururdu. Ev sahibi kadına epey borcu vardı ve onunla karşılaşmaktan çekiniyordu.\r\n\r\nKorkak ve çekingen biri değildi aslında. Tam tersine... Ama bir süredir tedirgindi. Öylesine kendi içine kapanmış, öylesine herkesten kopmuştu ki, yalnızca ev sahibesiyle değil, kiminle olursa olsun karşılaşmaktan kaçınıyordu. Ezen bir yoksulluk içindeydi ama şu son günlerde buna bile aldırdığı yoktu.', 'Roman|Dünya Klasikleri', 'https://1.bp.blogspot.com/-FKURuLxXV-w/Wgbeu4IUWSI/AAAAAAAAAAg/Vl9phHTG3JE6vpprPaZpVM3_z3VGl9PmACLcBGAs/s1600/0000000713226-1.jpg', 573546);

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `db1`
--
ALTER TABLE `db1`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `db1`
--
ALTER TABLE `db1`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
